-- 大井予想AI: Supabase スキーマ
-- Supabase ダッシュボード → SQL Editor に貼り付けて実行

create table if not exists oi_live_results (
    id bigint generated by default as identity primary key,
    race_date date not null,
    race_no integer not null,
    finish_order text not null,           -- 例: "5,3,8" 着順順の馬番CSV
    source text default 'manual',          -- 'manual' | 'scraped'
    inserted_at timestamptz default now(),
    constraint oi_live_results_unique unique (race_date, race_no)
);

create table if not exists oi_live_bias (
    race_date date primary key,
    bias_inner real,
    bias_front real,
    inner_top3_rate real,
    outer_top3_rate real,
    front_top3_rate real,
    late_top3_rate real,
    sample_size integer,
    computed_at timestamptz default now()
);

create table if not exists oi_live_predictions (
    id bigint generated by default as identity primary key,
    race_date date not null,
    race_no integer not null,
    payload jsonb not null,
    computed_at timestamptz default now()
);

create index if not exists oi_live_predictions_lookup
    on oi_live_predictions (race_date, race_no, computed_at desc);

-- 公開Read/書き込みポリシー（必要に応じて）
-- alter table oi_live_results enable row level security;
-- create policy "anon read" on oi_live_results for select using (true);
-- create policy "anon write" on oi_live_results for insert with check (true);
